### ISSUE TITLE
Just one id stream?

### ISSUE THREAD

**Issue by nickmers** [ikatson/docker-acestream-proxy#11]
Hello. Thanks a lot for the work. There are something to watch more that one stream? When I open two streams dont work. 

Regards

**Comment by ikatson** [comment]
Thanks @nickmers for kind words. To be fair I'm surprised this project still works at all, provided I haven't used it for years, or provided any support. 

So, sorry, no idea how to do that

**Comment by nickmers** [comment]
At end, it´s look like a general problem with acestream engine, not with proxy. Im testing other projects and there are same issue.

Your project is working despite of years.

Thanks for share.

Regards
