### ISSUE TITLE
output type xml rss

### ISSUE THREAD

**Issue by vinnitu** [ikatson/docker-acestream-proxy#3]
It will be very usefull to get different type of playlist by link

http://server:8000/torrenttv/torrenttv.m3u

with key in query &type=xml

PS: your solution with docker very nice. Do you try to deploy in raspberry pi?

**Comment by ikatson** [comment]
This is out of scope of this github repo, you should post an issue in the aceproxy repo instead https://github.com/ValdikSS/aceproxy.

I launch it on linux and Mac OSX, did not try directly on raspberry, I assume it will be hard or impossible.

**Comment by vinnitu** [comment]
yes, i see that is why i closed ticket ;-)
