### ISSUE TITLE
Raspberry Pi

### ISSUE THREAD

**Issue by woogie74** [ikatson/docker-acestream-proxy#4]
Hi I am struggling to get this image working on my raspberry PI. I have followed https://resin.io/blog/docker-on-raspberry-pi-in-4-simple-steps/ to built my RPi. I then ran, docker pull ikatson/aceproxy:latest. However if I try to run the container I get the following error

[error] server.go:1207 Handler for POST /containers/{name:.*}/start returned error: Cannot start container c985b3b5775856afbbcd17c6194cf27a16882b9a40aecc021d29565869891f8d: exec format error [error] server.go:110 HTTP Error: statusCode=500 Cannot start container c985b3b5775856afbbcd17c6194cf27a16882b9a40aecc021d29565869891f8d: exec format error 2015/01/18 12:15:12 Error response from daemon: Cannot start container c985b3b5775856afbbcd17c6194cf27a16882b9a40aecc021d29565869891f8d: exec format error I am pretty sure I am making a fundamental mistake but wondered if anyone could help me?

Many Thanks

**Comment by ikatson** [comment]
I never tried, but this should be due to diffent architectures.

Try building yourself for ARM. If it builds successfully, there's a small
chance it will work

docker build -t ikatson/aceproxy
git://github.com/ikatson/docker-acestream-proxy.git

**Comment by woogie74** [comment]
Hi Ikatson, thanks for your help. Unfortunatly the build on the RPi failed with the bellow error. I guess this is down to the ARM architecture?

exec format error[a27ec515] +job release_interface(d2642113c04c82e10814e242e1a78e78bfd82be504835d3c32b11d00b789582c)
[a27ec515] -job release_interface(d2642113c04c82e10814e242e1a78e78bfd82be504835d3c32b11d00b789582c) = OK (0)
[a27ec515] +job release_interface(d2642113c04c82e10814e242e1a78e78bfd82be504835d3c32b11d00b789582c)
[a27ec515] -job release_interface(d2642113c04c82e10814e242e1a78e78bfd82be504835d3c32b11d00b789582c) = OK (0)
exec format error
[a27ec515] -job build() = ERR (1)
2015/01/19 20:02:08 exec format error

Again thanks for your help

**Comment by ikatson** [comment]
Your problem is that the ```ubuntu:12.04``` image, that the Dockerfile is for, is x86_64.
For raspberry, you should use something like 

    FROM resin/rpi-raspbian 

in the Dockerfile. Notice, that ```aceengine``` is downloaded from the official repos for ubuntu precise. I doubt there are compiled binaries there for raspbian or any ARM at all.

You can try to change the Dockerfile to use the older leaked acestream from here
https://github.com/tarasian666/acestream

I never used it, and I have no idea if it works at all, so can't help here.

**Comment by ikatson** [comment]
I made that leaked acestream start with the following dockerfile. Can't test if it works, but that should be a good starting point for you. I've just tested that it at least listens on those exposed ports.

Please tell, if you manage to make it work.

```
FROM ubuntu:14.04
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -y
RUN apt-get install -y python-m2crypto python-apsw

ADD ./ /src/

EXPOSE 6878 8621 62062

ENTRYPOINT ["python", "/src/start.py"]
```

**Comment by ikatson** [comment]
Closing as irrelevant.

**Comment by woogie74** [comment]
Hi Ikatson
Very sorry I have not been able to reply untill now. Once again thank you for all your help and advice. Unfortunatly the older leaked Ace stream engine you have mentioned will not play video streams which have been created using a newer version of the engine but will however run on ARM architecture. With this in mind I am looking at Sopcast as a way to way to stream live video on a raspberry PI.

**Comment by ikatson** [comment]
Btw, maybe this can help:
https://github.com/enen92/P2P-Streams-Kodi

I did not inspect deeply, but looks like it natively works with acestream streams, without the need for acestream itself.

Not sure if you use XBMC, but anyway take a look
