### ISSUE TITLE
[Enhancement] start.sh params

### ISSUE THREAD

**Issue by jllodra** [ikatson/docker-acestream-proxy#5]
Hi,

first of all, this Docker container is very useful.

I'd like to modify the "maxconns" property in aceconfig.py, I see you use "sed" in the start.sh file to modify some params.
maxconns is 10 by default, so switching to a higher value would help in some cases.

What do you think about it?

**Comment by stanleylhs** [comment]
+1

@ikatson Any chance for this get implemented? Sorry for tagging you for a 3 years old post.

But this container is certainly the best AceStream solution for MacOS users. Thank you.

**Comment by jllodra** [comment]
@stanleylhs Take a look at https://www.sodaplayer.com/

**Comment by ikatson** [comment]
@stanleylhs please feel free to submit a PR, sounds like a very simple change.
