### ISSUE TITLE
[Enhancement] Viewing stream details

### ISSUE THREAD

**Issue by NDuggan** [ikatson/docker-acestream-proxy#7]
Well done on such a great Docker image - I used it the first time last night and it is so much better than running Wine and AceStream directly on my Mac.

Sorry if there is already a way to do this but I can't see/find it…

It would be great if I could see the details such as how many peers I am connected to and the percentage buffered, as I currently click play in VLC and then just have to wait.

**Comment by ikatson** [comment]
Thanks @NDuggan, I'm surprised it still works, as I haven't used it in years. I'm not the upstream developer, and as far as I know the upstream project (aceproxy) is not supported anymore.

So you are lucky you made it work in the first place. How did you use the image? Did you use it with torrent tv by buying a key from them or some other way?

**Comment by NDuggan** [comment]
Oh really, well it has stood the test of time then!

I used it directly with an acestream link (from Reddit) and then watched via VLC network streams. But whilst it was connecting I had to just assume it was going to work, as opposed to seeing connected to X of X peers - X% buffered. I've never heard of the place you mentioned though.

**Comment by ikatson** [comment]
Got it, I totally forgot this is useful for acestream links in general, not just russian "torrent.tv" thing.

I will close this ticket, as this is an upstream's concern. Here's aceproxy upstream for reference: https://github.com/ValdikSS/aceproxy
